name: healthbubba
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  
  google_fonts:
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  retry: ^3.1.2
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  agora_uikit: ^1.3.10
  equatable: ^2.0.5
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.8.1
  firebase_core: ^2.30.1
  flutter_tawkto: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  table_calendar: ^3.1.1
  change_app_package_name: ^1.3.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2.png"

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  
 